"""Release evidence bundle validation tests.

Fix #11: Separate source tests from release-evidence tests.

These tests validate the structure and content of evidence bundles
generated by benchmark runs, not the source code itself.
"""
from __future__ import annotations

import pytest


@pytest.mark.portable
def test_bundle_structure():
    """Test that evidence bundles have the required top-level structure."""
    # This is a placeholder test that would validate actual bundle structure
    # when evidence bundles are available
    required_fields = [
        "metadata",
        "results",
        "benchmark_methodology",
        "artifact_schema_version",
    ]

    # In actual use, this would load a real bundle and validate it
    # For now, we just verify the test infrastructure works
    assert len(required_fields) > 0


@pytest.mark.portable
def test_metadata_provenance():
    """Test that bundle metadata includes required provenance fields."""
    required_provenance_fields = [
        "token_sequence_hash",
        "git",
        "release_id",
    ]

    # In actual use, this would validate real bundle metadata
    assert len(required_provenance_fields) > 0


@pytest.mark.portable
def test_result_structure():
    """Test that individual result entries have required fields."""
    required_result_fields = [
        "name",
        "model_id",
        "prompt",
        "gate_status",
        "packed_attention_calls",
        "dense_fallback_calls",
        "packed_bytes_written",
        "packed_bytes_read",
    ]

    # In actual use, this would validate real result entries
    assert len(required_result_fields) > 0


@pytest.mark.portable
def test_promotion_eligibility_fields():
    """Test that promotion eligibility can be determined from bundle."""
    # This would use the PromotionPolicy to validate a candidate bundle
    from rfsn_v11.candidates.promotion_policy import PromotionPolicy

    policy = PromotionPolicy()

    # Create a minimal valid bundle for testing
    test_bundle = {
        "candidate": {
            "name": "test_candidate",
            "results": [],
        },
        "linked_baseline": {
            "name": "dense_mlx_baseline",
            "results": [],
        },
        "quality_evidence": [],
        "runtime_evidence": [],
        "memory_evidence": [],
        "speed_evidence": [],
        "provenance": {
            "token_sequence_hash": "test_hash",
            "token_sequence_provenance": {
                "token_sequence_artifact": "test_artifact",
                "token_sequence_artifact_sha256": "test_sha256",
            },
            "git": {
                "dirty": False,
            },
            "release_id": "test_release",
        },
    }

    # Test that build_candidate_bundle works
    # (This would be called with a real run_bundle in actual use)
    assert "candidate" in test_bundle
    assert "provenance" in test_bundle
